services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8081"
    volumes:
      - .:/app    # ローカル全体をコンテナの /app にマウント
      - /app/target  # /app/target を匿名ボリュームとして再定義（ローカル同期を解除）。これでローカルの target ディレクトリのマウントを防ぐ
    command: ./mvnw spring-boot:run
    environment:
      - JAVA_OPTS=-Dh2.tcpServer=true -Dh2.tcpPort=9192
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mydb_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
