# OASのバージョン
openapi: 3.0.0
# APIの一般情報
info:
  title: Tango API
  description: Web単語帳アプリTangoのAPIドキュメントです。
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/auth/register:
    post:
      summary: 新規ユーザー登録
      description: Tangoアプリケーションに新しいユーザーを登録します。
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequestDTO"
      responses:
        "201":
          description: ユーザーが正常に登録されました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponseDTO"
        "400":
          description: リクエストデータが無効です
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: コンフリクト - メールアドレスが既に登録されています
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/auth/login:
    post:
      summary: ユーザのログイン
      description: ユーザーを認証し、今後のリクエストに使用するJWTトークンを返します。
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequestDTO"
      responses:
        "200":
          description: ログインに成功しました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponseDTO"
        "401":
          description: 認証されていません - 資格情報が無効です
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/auth/logout:
    post:
      summary: ユーザーのログアウト
      description: 現在のユーザーをログアウトし、セッションまたはトークンを無効化します。
      tags:
        - Authentication
      responses:
        "200":
          description: ログアウトに成功しました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "401":
          description: 認証エラー - トークンが無効または欠落しています
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/users/{id}:
    get:
      summary: ユーザー情報の取得
      description: 指定されたIDでユーザーの情報を取得します。
      tags:
        - User
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 取得するユーザーのID。
      responses:
        "200":
          description: ユーザー情報が正常に取得されました。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponseDTO"
        "404":
          description: ユーザーが見つかりません。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/cardbooks:
    get:
      summary: すべてのカードブックを取得
      description: ログインしているユーザーが登録したすべてのカードブックを取得します。
      tags:
        - Cardbook
      responses:
        "200":
          description: カードブック一覧の取得に成功しました。
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CardbookResponse"
        "400":
          description: 認証が必要です。ログインしてください。
    post:
      summary: カードブックを新規作成
      description: 新しいカードブックを作成します。
      tags:
        - Cardbook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardbookRequest"
      responses:
        "201":
          description: カードブックが正常に作成されました。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardbookResponse"
        "400":
          description: 入力データが無効です。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラーです。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/cardbooks/{id}:
    put:
      tags:
        - Cardbook
      summary: カードブックを更新
      description: 指定したIDのカードブックを更新します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 更新するカードブックのID。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: カードブックの新しい名前。
                  example: "Updated Cardbook Name"
                description:
                  type: string
                  description: カードブックの新しい説明。
                  example: "This is the updated description for the cardbook."
              required:
                - name
      responses:
        "200":
          description: カードブックの更新に成功しました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 更新されたカードブックのID。
                    example: 1
                  name:
                    type: string
                    description: 更新後のカードブックの名前。
                    example: "Updated Cardbook Name"
                  description:
                    type: string
                    description: 更新後のカードブックの説明。
                    example: "This is the updated description for the cardbook."
        "400":
          description: 無効なリクエスト。
        "404":
          description: 指定したIDのカードブックが見つかりません。
        "500":
          description: サーバーエラー。
    delete:
      tags:
        - Cardbook
      summary: カードブックを削除済みステータスに移動
      description: 指定したIDのカードブックを削除済みステータスに変更します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 削除するカードブックのID。
      responses:
        "200":
          description: カードブックを削除済みステータスに移動しました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 削除されたカードブックのID。
                    example: 1
        "404":
          description: 指定されたカードブックが見つかりません。
        "500":
          description: サーバーエラー。

  /api/deleted-cardbooks/{id}:
    delete:
      tags:
        - Deleted Cardbook
      summary: 削除済みカードブックを完全に削除
      description: 削除済みカードブックをデータベースから完全に削除します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 完全に削除するカードブックのID。
      responses:
        "204":
          description: 削除済みカードブックの完全削除に成功しました。
        "404":
          description: 指定されたカードブックが見つかりません。
        "500":
          description: サーバーエラー。

  /api/deleted-cardbooks:
    get:
      tags:
        - Deleted Cardbook
      summary: 削除済みカードブックの一覧を取得
      description: ログインしているユーザーの削除済みカードブックを取得します。
      responses:
        "200":
          description: 削除済みカードブックの取得に成功しました。
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: カードブックのID。
                    name:
                      type: string
                      description: カードブックの名前。
                    deleted_date:
                      type: string
                      format: date-time
                      description: 削除日時。

  /api/cards:
    get:
      summary: すべてのカードを取得
      description: ログインしているユーザーが登録した全てのカードを取得します。
      tags:
        - Card
      responses:
        "200":
          description: カード一覧の取得に成功しました。
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CardResponse"
        "401":
          description: 認証が必要です。ログインしてください。
    post:
      summary: カードを新規作成
      description: 新しい単語カードを作成します。
      tags:
        - Card
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CardRequest"
      responses:
        "201":
          description: カードが正常に作成されました。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardResponse"
        "400":
          description: 入力データが無効です。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: サーバーエラーです。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/cards/{id}:
    put:
      tags:
        - Card
      summary: カードの更新
      description: 指定したIDのカードの内容を更新します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 更新するカードのID。
      responses:
        "200":
          description: カードの更新に成功しました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: 更新されたカードのID。
                    example: 1
                  name:
                    type: string
                    description: 更新後のカードの名前。
                    example: "Updated Card Name"
                  description:
                    type: string
                    description: 更新後のカードの説明。
                    example: "This is the updated description for the card."
        "400":
          description: 無効なリクエスト。
        "404":
          description: 指定したIDのカードが見つかりません。
        "500":
          description: サーバーエラー。
    delete:
      tags:
        - Card
      summary: カードを削除
      description: 指定したIDのカードを削除します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 削除するカードのID。
      responses:
        "204":
          description: カードの削除に成功しました。
        "404":
          description: 指定されたカードが見つかりません。
        "500":
          description: サーバーエラー。

  /api/cards/search:
    get:
      tags:
        - Card
      summary: カード検索
      description: 指定したキーワードでカードを検索します。
      parameters:
        - name: keyword
          in: query
          required: true
          schema:
            type: string
          description: 検索するキーワード。単語または定義の部分一致で検索されます。
      responses:
        "200":
          description: 検索結果を返します。
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalCount:
                    type: integer
                    description: 検索結果の総数。
                    example: 25
                  currentPage:
                    type: integer
                    description: 現在のページ番号。
                    example: 1
                  totalPages:
                    type: integer
                    description: 総ページ数。
                    example: 3
                  cards:
                    type: array
                    items:
                      $ref: "#/components/schemas/CardResponse"
        "400":
          description: 無効なリクエストパラメータ。
        "500":
          description: サーバーエラー。

  /api/cards/{id}/memorization:
    put:
      tags:
        - Card
      summary: 暗記度管理
      description: 暗記度を三段階（0：未記憶, 1：部分的に記憶, 2：完全記憶）で管理します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 暗記度を更新するカードのID。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memorizationLevel:
                  type: integer
                  enum: [0, 1, 2]
                  description: 更新する暗記度レベル（0：未記憶, 1：部分的に記憶, 2：完全記憶）。
                  example: 1
              required:
                - memorizationLevel
      responses:
        "200":
          description: 暗記度の更新に成功しました。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardResponse"
        "400":
          description: 無効なリクエスト（例：不正な暗記度レベル）。
        "404":
          description: 指定されたカードが見つかりません。
        "500":
          description: サーバーエラー。

  /api/cardbooks/{id}/export:
    get:
      tags:
        - Cardbook
      summary: エクスポート
      description: 指定したIDのカードブックの内容をCSV形式でエクスポートします。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: エクスポート対象のカードブックID。
      responses:
        "200":
          description: 成功時にCSV形式のファイルが返されます。
          content:
            text/csv:
              schema:
                type: string
                format: binary
        "400":
          description: リクエストが無効な場合 (例:IDが存在しない場合)。
        "404":
          description: 指定されたIDのカードブックが存在しない場合。
        "500":
          description: サーバーエラーが発生した場合。

  /api/cardbooks/import:
    post:
      tags:
        - Cardbook
      summary: インポート
      description: 指定したカードブックにCSVファイルをインポートします。
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                cardbookId:
                  type: integer
                  description: インポート対象のカードブックID。
                file:
                  type: string
                  format: binary
                  description: インポートするCSVファイル。
      responses:
        "200":
          description: 成功時にインポート結果が返されます。
          content:
            application/json:
              schema:
                type: object
                properties:
                  successCount:
                    type: integer
                    description: インポートに成功したカードの数。
                  failedCount:
                    type: integer
                    description: インポートに失敗したカードの数。
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        row:
                          type: integer
                          description: エラーが発生した行番号。
                        message:
                          type: string
                          description: エラーメッセージ。
        "400":
          description: リクエストが無効な場合 (例:ファイル形式がCSVではない、必須フィールドが欠落している)。
        "404":
          description: 指定されたカードブックが存在しない場合。
        "500":
          description: サーバーエラーが発生した場合。

  /api/public/cards/{id}:
    get:
      tags:
        - Public
      summary: カード閲覧(ログイン不要)
      description: ログイン不要でカードを閲覧します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: 閲覧対象のカードブックID。
      responses:
        "200":
          description: 指定されたカードブックのカードが正常に取得されました。
          content:
            application/json:
              schema:
                type: object
                properties:
                  cardbookId:
                    type: integer
                    description: カードブックID。
                  cards:
                    type: array
                    items:
                      $ref: "#/components/schemas/CardResponse"
        "400":
          description: リクエストが無効な場合 (例:IDが存在しない、または形式が不正)。
        "404":
          description: 指定されたカードブックが存在しない場合。
        "500":
          description: サーバーエラーが発生した場合。

components:
  schemas:
    RegisterRequestDTO:
      type: object
      properties:
        email:
          type: string
          format: email
          description: ユーザーのメールアドレス
        password:
          type: string
          format: password
          description: ユーザーのパスワード
      required:
        - email
        - password

    RegisterResponseDTO:
      type: object
      properties:
        userId:
          type: integer
          description: 新規作成されたユーザーのID
        message:
          type: string
          description: 登録確認メッセージ

    LoginRequestDTO:
      type: object
      properties:
        email:
          type: string
          format: email
          description: ユーザーのメールアドレス
        password:
          type: string
          format: password
          description: ユーザーのパスワード
      required:
        - email
        - password

    LoginResponseDTO:
      type: object
      properties:
        token:
          type: string
          description: 認証されたリクエストに使用する JWT トークン
        message:
          type: string
          description: ログイン成功メッセージ

    UserResponseDTO:
      type: object
      properties:
        userId:
          type: integer
          description: ユーザーの一意のID。
        email:
          type: string
          format: email
          description: ユーザーのメールアドレス。

    MessageResponse:
      type: object
      properties:
        message:
          type: string
          description: 成功または情報メッセージ。

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: 問題が発生した場合のエラーメッセージ。

    CardbookRequest:
      type: object
      properties:
        name:
          type: string
          description: カードブックの名前
          example: "英単語帳"
        description:
          type: string
          description: カードブックの説明
          example: "受験用英語の単語帳"

    CardbookResponse:
      type: object
      properties:
        id:
          type: integer
          description: カードブックの一意の識別子
          example: 1
        name:
          type: string
          description: カードブックの名前
          example: "英単語帳"
        description:
          type: string
          description: カードブックの説明
          example: "受験用英語の単語帳"

    CardRequest:
      type: object
      properties:
        term:
          type: string
          description: 単語やフレーズなど
          example: "programming"
        definition:
          type: string
          description: 単語の説明または定義
          example: "The process of creating software."

    CardResponse:
      type: object
      properties:
        id:
          type: integer
          description: カードの一意の識別子
          example: 1
        term:
          type: string
          description: 単語やフレーズなど
          example: "programming"
        definition:
          type: string
          description: 単語の説明または定義
          example: "The process of creating software."
        memorizationLevel:
          type: integer
          description: 暗記レベル（0：未暗記, 1：部分暗記, 2：暗記済）
          example: 2
