spring:
  application:
    name: Tango
  profiles:
    active: dev # デフォルトでは開発環境を使用
  security:
    enabled: false
  datasource:
    driver-class-name: org.h2.Driver # デフォルトではH2を設定
    url: jdbc:h2:tcp://0.0.0.0:9192/mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect


server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9192/mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      settings:
        web-allow-others: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/mydb
    username: prod_user
    password: prod_password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect




